name: CI

on:
    push:
        branches:
            - main
    pull_request:
        branches: [main]
    workflow_dispatch: {} # allow manual runs with toggles if needed

permissions:
    actions: read
    contents: read

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    main:
        runs-on: ubuntu-latest
        timeout-minutes: 15

        # CI + npm network behavior
        env:
            CI: true
            NPM_CONFIG_FETCH_RETRIES: '5'
            NPM_CONFIG_FETCH_RETRY_MINTIMEOUT: '20000' # 20s
            NPM_CONFIG_FETCH_RETRY_MAXTIMEOUT: '120000' # 120s
            NPM_CONFIG_TIMEOUT: '600000' # 10m
            NPM_IGNORE_SCRIPTS: 'false' # set to 'true' for diagnostic install
        
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  filter: tree:0
                  fetch-depth: 0

            # This enables task distribution via Nx Cloud
            # Run this command as early as possible, before dependencies are installed
            # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
            # Uncomment this line to enable task distribution
            # - run: npx nx start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"

            # Cache node_modules
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'npm'

            - run: npm ci --legacy-peer-deps
            - run: npx playwright install --with-deps

            # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
            # - run: npx nx-cloud record -- echo Hello World
            # When you enable task distribution, run the e2e-ci task instead of e2e
            - run: npx nx run-many -t lint test build typecheck e2e --cloud=false
            # Nx Cloud recommends fixes for failures to help you get CI green faster. Learn more: https://nx.dev/ci/features/self-healing-ci
            - run: npx nx fix-ci
              if: always()
